# Main Workflow
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  JAVA_VERSION: 1.15

jobs:
  my_first_job:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        env:
          MY_VAR: Hi there!
          FIRST_NAME: Java :))
        run: |
          echo $MY_VAR $FIRST_NAME is using version $JAVA_VERSION
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build Project
        run: mvn --no-transfer-progress clean install

      - name: Show path of jacoco reports
        run: ls -la target/site/jacoco/

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv

      - name: Log coverage percentage to the workflow log
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Committing JaCoCo Badge'
          add: '*.svg'